name: flutter_openmoji
description: '''OpenMoji is an open-source project of 50+ students and 2 professors of the HfG Schwäbisch Gmünd (Design University) and external contributers. This package bring those handcrafted magnciient emojis into your flutter projects.'''
version: 0.0.6
homepage: https://github.com/shalien/flutter_openmoji

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  path: ^1.8.2
  http: ^0.13.5

flutter:
  fonts:
     - family: OpenMoji-Black
       fonts:
         - asset: packages/flutter_openmoji/fonts/OpenMoji-Black.ttf
