name: flutter_openmoji
description: '''OpenMoji is an open-source project of 50+ students and 2 professors of the HfG Schwäbisch Gmünd (Design University) and external contributers. This package bring those handcrafted magnciient emojis into your flutter projects.'''
version: 0.0.8
homepage: https://github.com/shalien/flutter_openmoji

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  path: ^1.8.2
  http: ^0.13.5

flutter:
  fonts:
     - family: OpenMoji-Black-glyf
       fonts:
       - asset: packages/flutter_openmoji/fonts/OpenMoji-black-glyf.ttf
     - family: OpenMoji-Color-cbdt
       fonts:
         - asset: packages/flutter_openmoji/fonts/OpenMoji-color-cbdt.ttf
     - family: OpenMoji-Color-glyf_colr_0
       fonts:
         - asset: packages/flutter_openmoji/fonts/OpenMoji-color-glyf_colr_0.ttf     
     - family: OpenMoji-Color-glyf_colr_1
       fonts:
         - asset: packages/flutter_openmoji/fonts/OpenMoji-color-glyf_colr_1.ttf
     - family: OpenMoji-Color-picosvgz
       fonts:
         - asset: packages/flutter_openmoji/fonts/OpenMoji-color-picosvgz.ttf
     - family: OpenMoji-Color-sbix
       fonts:
         - asset: packages/flutter_openmoji/fonts/OpenMoji-color-sbix.ttf
     - family: OpenMoji-Color-untouchedsvgz
       fonts:
         - asset: packages/flutter_openmoji/fonts/OpenMoji-color-untouchedsvgz.ttf